### ISSUE TITLE
Question about paranoia mode on upgradepkg

### ISSUE THREAD

**Issue by vmmello** [mina86/pkgtools#1]
Hi,

I'm a Slackware user, and I have a question about the "paranoia" mode on upgradepkg. I'm asking it here as a Github issue, please let me know if there's somewhere else better to ask.

One thing I've always noticed, since the first time I read the code, is the following block near the end of the script:

```bash
  # Again!  Again!
  # Seriously, the reinstalling of a package can be crucial if any files
  # shift location, so we should always reinstall as the final step:
  if [ ! "$NOT_PARANOID" = "true" ]; then
    /sbin/installpkg $INCOMINGDIR/$NNAME
  fi
```

Then reading the parsing of the `--no-paranoia` option, there's the following:

```bash
  if [ "$1" = "--no-paranoia" ]; then
    # Enable --no-paranoia mode.  This is so not-recommended that we're
    # not even going to document it. ;)   If a file used to be directly
    # managed and now is moved into place, using --no-paranoia will cause
    # it to improperly disappear.  It does slightly speed things up, though.
    # Don't use it.
    NOT_PARANOID="true"
```

Though it's not clear to me what's the corner case that requires the package to be installed twice (I miss the context of phrases like `...reinstalling of a package can be crucial if any files shift location` and `If a file used to be directly managed and now is moved into place...`).

The impression that I've always had is that the files to be removed during the upgrade are the ones that exist on the old package, but don't exist on the new package (...and files that exist on both are kept) and that this logic was enough for a package upgrade. Though maybe I'm missing some corner cases.

Can you give an example of a situation where the double install fixes a problem caused by the prior steps?

Thanks in advance.

**Comment by mina86** [comment]
No idea. I've never really looked into that aspect of the code. You might try asking on Slackware board of LinuxQuestions.org.

**Comment by vmmello** [comment]
Ok, thanks.
